### ISSUE TITLE
Splitting attributes in TSX slightly weird

### ISSUE THREAD

**Issue by onlyfortesting** [Wansmer/treesj#8]
I'm trying to split attributes in TSX with:

```lua
local tsj = require('treesj')
local u = require('treesj.langs.utils')
local typescript = require('treesj.langs.typescript')

tsj.setup({
  use_default_keymaps = false,
  max_join_length = 9999,
  langs = {
    tsx = u.merge_preset(typescript, {
      jsx_opening_element = u.set_default_preset({
        both = {
          omit = { 'identifier' },
        },
      }),
      jsx_self_closing_element = u.set_default_preset({
        both = {
          omit = { 'identifier' },
          no_format_with = {},
        },
      }),
    })
  },
})
    
```
This is the results I've got:
```jsx
<PageCanvas
  class="px-2 py-1"
  canvasClass={clsx("page-thumbnail-canvas mx-auto shadow", props.active && 'ring-4')}
  page={props.page}
  zoom={() => 0.28}
  onUpdate={props.onUpdate}
  /
>
```
Notice the character `/` and `>` at the end also got split? How to fix this?
Thank you.

**Comment by Wansmer** [comment]
I'll fix it, unexpected what '/' in tsx is a separate node.
Btw, you don't need merge typescript for tsx, because treesitter already recognize typescript in txs. You just need:
```lua
langs = {
  tsx = {
    jsx_opening_element = u.set_default_preset(--[[ ... ]]),
    --[[ ... ]]
  }
}
```

**Comment by Wansmer** [comment]
As a temporary solution you can add '>' to 'omit' in jsx_self_closing_element, but the last indent will still be wrong.

**Comment by onlyfortesting** [comment]
> I'll fix it, unexpected what '/' in tsx is a separate node. Btw, you don't need merge typescript for tsx, because treesitter already recognize typescript in txs. You just need:
> 
> ```lua
> langs = {
>   tsx = {
>     jsx_opening_element = u.set_default_preset(--[[ ... ]]),
>     --[[ ... ]]
>   }
> }
> ```

I tried, but it doesn't work. I got this when trying splitting array (or any other node except the ones I manually configured):
```
[TreeSJ]: Node "array" for lang "tsx" is not configured
```

**Comment by Wansmer** [comment]
> > I'll fix it, unexpected what '/' in tsx is a separate node. Btw, you don't need merge typescript for tsx, because treesitter already recognize typescript in txs. You just need:
> > ```lua
> > langs = {
> >   tsx = {
> >     jsx_opening_element = u.set_default_preset(--[[ ... ]]),
> >     --[[ ... ]]
> >   }
> > }
> > ```
> 
> I tried, but it doesn't work. I got this when trying splitting array (or any other node except the ones I manually configured):
> 
> ```
> [TreeSJ]: Node "array" for lang "tsx" is not configured
> ```

I checked, you are right. I fixed the problem with '/' and added default preset for tsx/jsx (now you can delete additional configuration from setup). Please, let me know if it's working wrong. Thank you for sharing the issue.

**Comment by onlyfortesting** [comment]
Working perfectly. Thank you!

**Comment by onlyfortesting** [comment]
Oh, I see that you also added jsx support as well. However, for jsx the behavior is still not correct.
I thought the problem was this line (merging `treesj.langs.typescript` instead of `treesj.langs.javascript`)
https://github.com/Wansmer/treesj/blob/a250e87edcbcf96a5ac22adbcb82c1431edfd274/lua/treesj/langs/jsx.lua#L2
But even after I changed it, the behavior is still not correct.

**Comment by Wansmer** [comment]
@onlyfortesting, send me a segment of code jsx where you call a plugin, please

**Comment by onlyfortesting** [comment]
```jsx
function PageButton(props) {
  return (
    <button class="p-2 rounded hover:bg-gray-200" {...rest}>
      <Icon class="w-5 h-5"></Icon>
    </button>
  )
}
```
I'm calling on `button`

**Comment by Wansmer** [comment]
It really strange behavior of tree-sitter: it recognize jsx code like javascript. If add presets for jsx elements to javascript - it work well (and need add object_pattern too). Later I will do this changes and merge it to master.

**Comment by Wansmer** [comment]
Fixed with #14 
Hope, now it works as expected :-)
